### ISSUE TITLE
Problem with json array request body

### ISSUE THREAD

**Issue by dsgr** [radAdam/wiremock-velocity-transformer#14]
Hello!
I`m use wiremock-velocity-transformer-standalone-2.2.jar and when request body is JSON ARRAY - error response is returned:

```
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Error 500 Server Error</title>
</head>

<body>
	<h2>HTTP ERROR 500</h2>
	<p>Problem accessing /testUrl. Reason:
		<pre>    Server Error</pre>
	</p>
	<h3>Caused by:</h3>
	<pre>java.lang.ClassCastException: net.minidev.json.JSONArray cannot be cast to net.minidev.json.JSONObject
	at com.github.adamyork.wiremock.transformer.VelocityResponseTransformer.lambda$null$11(VelocityResponseTransformer.java:137)
	at org.jooq.lambda.Unchecked.lambda$supplier$37(Unchecked.java:1647)
	at com.github.adamyork.wiremock.transformer.VelocityResponseTransformer.lambda$addBodyToContext$12(VelocityResponseTransformer.java:140)
	at java.util.Optional.orElseGet(Unknown Source)
	at com.github.adamyork.wiremock.transformer.VelocityResponseTransformer.addBodyToContext(VelocityResponseTransformer.java:134)
	at com.github.adamyork.wiremock.transformer.VelocityResponseTransformer.lambda$transform$1(VelocityResponseTransformer.java:69)
	at java.util.Optional.map(Unknown Source)
	at com.github.adamyork.wiremock.transformer.VelocityResponseTransformer.transform(VelocityResponseTransformer.java:60)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.applyTransformations(InMemoryStubMappings.java:98)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:79)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:179)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:50)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:47)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)
</pre>
	<hr><i><small>Powered by Jetty://</small></i>
	<hr />

</body>

</html>
```

**Comment by dsgr** [comment]
problem fixed in version 2.3
