### ISSUE TITLE
Velocity templates not found when templates not in child directory

### ISSUE THREAD

**Issue by PieterVanEde** [radAdam/wiremock-velocity-transformer#9]
In our project (were we use Wiremock standalone) we recently moved all our mocks. Now they are no longer in a child directory of the wiremock location. For Wiremock we needed to pass the rootDir parameter, but unfortunately all our mocks that used Velocity templates failed. As a result the response would yield a HTTP 500 error and a ResourceNotFound in the stacktrace.

The problem is that the currentl implementation passes a full path to Velocity, even if the FileResourceLoader has not loaded the templates from that directory. Hence the ResourceNotFound.

**Comment by PieterVanEde** [comment]
This is the response wiremock yields for GET and POST method requests:

`<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /api/paymentssavings/orders/createorder. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource &apos;/Users/xx/Development/senses/senses/mocks/rbo/__files/server/make-payment/data-createorder-stub.vm&apos;
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:462)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:343)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1554)
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1534)
	at org.apache.velocity.runtime.RuntimeSingleton.getTemplate(RuntimeSingleton.java:275)
	at org.apache.velocity.app.Velocity.getTemplate(Velocity.java:288)
	at com.github.adamyork.wiremock.transformer.VelocityResponseTransformer.getRenderedBody(VelocityResponseTransformer.java:154)
	at com.github.adamyork.wiremock.transformer.VelocityResponseTransformer.transform(VelocityResponseTransformer.java:71)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.applyTransformations(InMemoryStubMappings.java:98)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:79)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:179)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:50)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:47)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:844)
</pre>
<hr><i><small>Powered by Jetty://</small></i><hr/>
​
</body>
</html>`

**Comment by PieterVanEde** [comment]
Apart from this fix, you might also consider to not use VelocityEngine at all, but use Velocity.init(Properties). I didn't have time to investigate that further, perhaps tomorrow.

**Comment by adamyork** [comment]
Okay seems reasonable. I don't believe I have ever used that command line feature of the standalone runner.

**Comment by adamyork** [comment]
Okay I have merged your changes into HEAD and tested. Published new standalone release, https://github.com/adamyork/wiremock-velocity-transformer/releases/tag/2.1-release. I have not yet published the artifact to maven central. That will take a bit of a time. Hope this moves you forward. Thanks for the contribution.

**Comment by PieterVanEde** [comment]
Great, thanks for incorporating my fixes!
